# Generated by Django 3.0.5 on 2022-07-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_details',
            name='authority_code',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='license_details',
            name='dl_no',
            field=models.CharField(default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='license_details',
            name='holder_name',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='license_details',
            name='license_authority',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='license_details',
            name='vehicle_class',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
