# Generated by Django 3.0.5 on 2022-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0002_auto_20220701_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_details',
            name='dob',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
