# Generated by Django 3.0.5 on 2022-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='I_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('engine_no', models.CharField(default=0, max_length=13)),
                ('chassis_no', models.CharField(default=0, max_length=17)),
                ('registration_no', models.CharField(default=0, max_length=10)),
                ('owner_name', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
