# Generated by Django 3.0.5 on 2022-07-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminDashboard', '0002_auto_20220701_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='RC_Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_no', models.CharField(max_length=20)),
                ('chassis_no', models.CharField(max_length=20)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.RC_Details')),
            ],
        ),
    ]
